jsio_compile:
	node -e "require('./jsio/jsio');jsio('import .build').run(true);"
	cp build/jsio_compile ../../

debug:
	node -e "require('./jsio/jsio');jsio('import .build').run(false);"
	cp build/jsio_compile ../../
