jsio_compile:
	node -e "var jsio=require('../../');jsio('import .build').run(true);"
	cp build/jsio_compile ../../

debug:
	node -e "var jsio=require('../../');jsio('import .build').run(false);"
	cp build/jsio_compile ../../
